platform :ios, '13.4'
use_frameworks! :linkage => :static
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def pod_Debug
  pod 'SwiftLint', '~> 0.52.2', :configurations => ['Debug']
  pod 'LookinServer', '~> 1.1.7', :subspecs => ['Swift'], :configurations => ['Debug']
end

target 'FlexibleBoxExample' do
  pod 'FlexibleBox', :path => '..'
  pod 'Yoga', :git => 'https://github.com/facebook/yoga.git', :inhibit_warnings => true
  pod 'YogaKit', :git => 'https://github.com/facebook/yoga.git', :inhibit_warnings => true

  pod_Debug
end