platform :ios, '13.0'
use_frameworks! :linkage => :static
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def pod_FlexibleBox
  pod 'FlexibleBox', :path => '..'
  pod 'YogaKit', '~> 2.0.0-beta.1'
end

def pod_Debug
  pod 'SwiftLint', '~> 0.52.3', :configurations => ['Debug']
  pod 'LookinServer', '~> 1.1.7', :subspecs => ['Swift'], :configurations => ['Debug']
end

target 'FlexibleBoxExample' do
  pod_FlexibleBox
  pod_Debug
end
